In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__


'2.15.0'

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/machine learning udemy r/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv')

In [ ]:
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values



In [ ]:
#label encoding the gender column ie 0 and 1

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
#now one hot encodeing the geography

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')# 1 is the column index
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
X_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

In [ ]:
#FEATURE SCALING : IT IS ABSOLUTELY NECESSARY TO FEATURE SCALE FOR DEEP LEARNING RERGARDLESS OF 0 AND 1
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)



In [ ]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [ ]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

#BUILDING THE ANN

In [ ]:
#CREATE THE ANN

#initialize

ann = tf.keras.models.Sequential()

In [ ]:
#add input layer and first hidden layer

ann.add(  tf.keras.layers.Dense( units = 6 , activation = 'relu')) #adding the dense class

#units is the no of neurons in ffirst hidden layer...random no rule
#activation = '' == activation function layer
#relu = rectifier activation function

#add 2nd hidden layer

ann.add(  tf.keras.layers.Dense( units = 6 , activation = 'relu'))

#change the no . of units for diff result



In [ ]:
#output layer

ann.add(  tf.keras.layers.Dense( units = 1 , activation = 'sigmoid'))


#since we need only binary out put like 1 or 0 we need only one neuron ie dimension
#but if it was classification with 2 or more classes like a b and c, we would need 3 o/p neuron ie 3 dimensions
#and we would need to one hot encode the three classes as well like a= 100 , b =010 and c = 001,,so on

#TRAINING THE ANN

In [ ]:
#compile the ann




ann.compile( optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

#optimizer = 'adam' best for schtocastic gdm
#loss = 'binary_crossentropy' for binary classification
#loss = 'categorical_crossentropy' for non-binary classification

#and for non-binary classification with more than 2 classification the o/p activation functoin should be 'softmax' not 'sigmoid'
#metrics = ['accuracy']  for evaluation







In [ ]:
#Training the ANN on the Training set





ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 6s 6ms/step - loss: 0.6779 - accuracy: 0.6136
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5141 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4739 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4468 - accuracy: 0.8031
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4295 - accuracy: 0.8139
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4214 - accuracy: 0.8158
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4154 - accuracy: 0.8199
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4105 - accuracy: 0.8235
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4039 - accuracy: 0.8263
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3960 - accura


Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?


In [ ]:
test = sc.transform([[ 1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])#ann was trained with scaled value
test

array([[ 0.98560362, -0.5698444 , -0.57369368, -0.52111599,  0.91601335,
         0.10961719, -0.68538967, -0.2569057 ,  0.8095029 ,  0.64259497,
         0.9687384 , -0.87203322]])

In [ ]:
prediction = ann.predict(test)
prediction

1/1 [==============================] - 0s 38ms/step


array([[0.02804506]], dtype=float32)

In [ ]:
print(prediction > 0.5)

[[False]]


In [ ]:
#prediction > 0.5 == 1 bcoz of sigmoid function

#here false means the customer will not leave the bank

Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))



63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1527   68]
 [ 207  198]]


0.8625