In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [9]:
dataset = pd.read_csv('/content/drive/MyDrive/modeol selection/Machine Learning A-Z (Model Selection)/Classification/Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.25 , random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

decision tree classifier

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
dtc = accuracy_score(y_test, y_pred)
print(dtc)

[[103   4]
 [  3  61]]
0.9590643274853801


KNN


In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
knn = accuracy_score(y_test, y_pred)
knn

[[103   4]
 [  5  59]]


0.9473684210526315

kernel svm


In [14]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
ksvm = accuracy_score(y_test, y_pred)
ksvm

[[102   5]
 [  3  61]]


0.9532163742690059

svm

In [15]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svm = accuracy_score(y_test, y_pred)
svm

[[102   5]
 [  5  59]]


0.9415204678362573

logistic regression

In [16]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
lr = accuracy_score(y_test, y_pred)
lr

[[103   4]
 [  5  59]]


0.9473684210526315

naive bayes

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
nb = accuracy_score(y_test, y_pred)
nb

[[99  8]
 [ 2 62]]


0.9415204678362573

random forest

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
rf = accuracy_score(y_test, y_pred)
rf

[[102   5]
 [  6  58]]


0.935672514619883

evaluating

In [19]:
print("linear regression",lr)
print("k kearest neighbor",knn)
print("svm",svm)
print("kernel svm",ksvm)
print("naive bayes",nb)
print("decision tree",dtc)
print("random forest",rf)

linear regression 0.9473684210526315
k kearest neighbor 0.9473684210526315
svm 0.9415204678362573
kernel svm 0.9532163742690059
naive bayes 0.9415204678362573
decision tree 0.9590643274853801
random forest 0.935672514619883
