In [ ]:

from google.colab import drive
drive.mount('/content/drive')



import numpy as np
import pandas as pd
import tensorflow as tf

Mounted at /content/drive


In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/machine learning udemy r/projects/nlp/sentimentdataset.csv')

In [ ]:
dataset.describe
sentiment = dataset['Sentiment']

In [ ]:
sentiment


0       Positive  
1       Negative  
2       Positive  
3       Positive  
4       Neutral   
          ...     
727         Happy 
728         Happy 
729         Happy 
730         Happy 
731         Happy 
Name: Sentiment, Length: 732, dtype: object

In [ ]:
print(sentiment[100:500])

100     Acceptance   
101     Excitement   
102     Bitter       
103     Calmness     
104        Confusion 
            ...      
495              Awe 
496         Serenity 
497        Amazement 
498          Romance 
499              Awe 
Name: Sentiment, Length: 400, dtype: object


In [ ]:
print(sentiment.unique())

[' Positive  ' ' Negative  ' ' Neutral   ' ' Anger        '
 ' Fear         ' ' Sadness      ' ' Disgust      ' ' Happiness    '
 ' Joy          ' ' Love         ' ' Amusement    ' ' Enjoyment    '
 ' Admiration   ' ' Affection    ' ' Awe          ' ' Disappointed '
 ' Surprise     ' ' Acceptance   ' ' Adoration    ' ' Anticipation '
 ' Bitter       ' ' Calmness     ' ' Confusion    ' ' Excitement   '
 ' Kind         ' ' Pride        ' ' Shame        ' ' Confusion '
 ' Excitement ' ' Shame ' ' Elation       ' ' Euphoria      '
 ' Contentment   ' ' Serenity      ' ' Gratitude     ' ' Hope          '
 ' Empowerment   ' ' Compassion    ' ' Tenderness    ' ' Arousal       '
 ' Enthusiasm    ' ' Fulfillment  ' ' Reverence     ' ' Compassion'
 ' Fulfillment   ' ' Reverence ' ' Elation   ' ' Despair         '
 ' Grief           ' ' Loneliness      ' ' Jealousy        '
 ' Resentment      ' ' Frustration     ' ' Boredom         '
 ' Anxiety         ' ' Intimidation    ' ' Helplessness    '
 ' 

In [ ]:
positive_words = ['positiveReunion ' ,' Runwaypositive' ," Ocean'spositive",'positive ','positive  ' ,' positive ', 'positive    ', 'positive      ', 'positive ', 'positive     ','positive   ', 'positive  ' ,' positive','positive  ' ,' positive ',' positive   ','Positive', 'Happiness', 'Joy', 'Love', 'Amusement', 'Enjoyment', 'Admiration', 'Affection', 'Awe', 'Acceptance', 'Adoration', 'Anticipation', 'Calmness', 'Excitement', 'Kind', 'Pride', 'Elation', 'Euphoria', 'Contentment', 'Serenity', 'Gratitude', 'Hope', 'Empowerment', 'Compassion', 'Tenderness', 'Arousal', 'Enthusiasm', 'Fulfillment', 'Reverence', 'Determination', 'Zest', 'Hopeful', 'Proud', 'Grateful', 'Empathetic', 'Compassionate', 'Playful', 'Free-spirited', 'Inspired', 'Confident', 'Curiosity', 'Ambivalence', 'Bitterness', 'Yearning', 'Confidence', 'Surprise', 'Accomplishment', 'Wonderment', 'Optimism', 'Playful Joy', 'Mindfulness', 'Dream Chaser', 'Elegance', 'Whimsy', 'Pensive', 'Harmony', 'Creativity', 'Radiance', 'Wonder', 'Rejuvenation', 'Coziness', 'Adventure', 'Euphoria', 'Melodic', 'Festive Joy', 'Inner Journey', 'Freedom', 'Dazzle', 'Adrenaline', 'Artistic Burst', 'Resilience', 'Immersion', 'Spark', 'Marvel', 'Serenity', 'Positivity', 'Kindness', 'Friendship', 'Colorful', 'Pride', 'Hypnotic', 'Connection', 'Iconic', 'Journey', 'Engagement', 'Touched', 'Satisfaction', 'Admiration', 'Triumph', 'Heartwarming', 'Sympathy', 'Renewed Effort', 'Challenge', 'Solace', 'Breakthrough', 'Harmony', 'Joy in Baking', 'Envisioning History', 'Imagination', 'Vibrancy', 'Mesmerizing', 'Culinary Adventure', 'Winter Magic', 'Thrilling Journey', "Nature's Beauty", 'Celestial Wonder', 'Creative Inspiration', 'Runway Creativity', "Ocean's Freedom", 'Whispers of the Past', 'Boredom', 'Indifference', 'Disgust', 'Relief', 'Positive', 'Embarrassed', 'Mischievous', 'Sad', 'Hate', 'Bad', 'Neutral', 'Happy', 'positiveness', 'positiveful', 'positiveate', 'Thrill', 'negativesweet', 'Overjoyed', 'Inspiration', 'Motivation', 'Appreciation', 'Enchantment', 'positivefulReunion', 'Blessed', 'Intrigue', 'positivepositive', 'DreamChaser', 'Thrill', 'Inspiration', 'Festivepositive', 'Innerpositive', 'ArtisticBurst', 'Inspiration', 'Lostpositive', 'positiveness', 'Success', 'Thrill', 'Enchantment', 'Exploration', 'Amazement', 'Romance', 'Captivation', 'Tranquility', 'Grandeur', 'Emotion', 'Energy', 'Celebration', 'Charm', 'Ecstasy', 'positive in Baking', 'Culinary positive', 'Thrilling positive', 'Celestial positive', 'Runway positive', "Ocean's positive", ' positiveing positive ' ,' positivealStorm ' ,' positiveReunion ',' positive  ' ,'positivealStorm ' ,'positivein Baking ',' Culinarypositive' ,'positiveingpositive' ,' Celestialpositive']

negative_words = ['negativeful ',' negative', 'negative ','negative', 'negative ',' negative ' ,' negative       ' ,' negative    ','negative   ', ' negative      ',' negative     ' ,'negative    ' ,' negative   ' , 'negative  ',' Negative  ' ,' negative        ' ,' negative         ','Anger', 'Fear', 'Sadness', 'Disgust', 'Disappointed', 'Shame', 'Confusion', 'Bitter', 'Loneliness', 'Jealousy', 'Resentment', 'Frustration', 'Boredom', 'Anxiety', 'Intimidation', 'Helplessness', 'Envy', 'Regret', 'Despair', 'Grief', 'Betrayal', 'Suffering', 'Emotional Storm', 'Darkness', 'Desperation', 'Ruins', 'Desolation', 'Regret', 'Grief', 'Heartbreak', 'Betrayal', 'Sorrow', 'Loss', 'Heartache', 'Solitude', 'Sad', 'Hate', 'Bad', 'Embarrassed', 'Mischievous',' negativeful ', ' Apprehensive ', ' Overwhelmed ', ' Jealous ', ' Devastated ', ' Frustrated ', ' Envious ' ,' Dismissive ',' Overwhelmed   ', ' Contemplation ' ,' Obstacle ' ,' Pressure ' ,' Miscalculation ',' CulinaryOdyssey ', ' Isolation ' ,' Disappointment ',' Exhaustion ']

neutral_words = [' neutral' ,'neutral ',' neutral        ',' neutral      ', ' neutral       ' ,' neutral ','neutral   ' ,' neutral     ' ,'neutral','Neutral', 'Confusion', 'Numbness', 'Melancholy', 'Nostalgia', 'Ambivalence', 'Indifference', 'Curiosity', 'Disgust', 'Numbness', 'Zest', 'Contentment', 'Neutral',' Reflection ' ,' Suspense ']



In [ ]:



# Replace positive words with "positive" in the specified column
dataset['Sentiment'] = dataset['Sentiment'].replace(positive_words, 'positive', regex=True, )
dataset['Sentiment'] = dataset['Sentiment'].replace(negative_words, 'negative', regex=True, )
dataset['Sentiment'] = dataset['Sentiment'].replace(neutral_words, 'neutral', regex=True, )

# Display the modified DataFrame
print(dataset['Sentiment'])


0      positive
1      negative
2      positive
3      positive
4      positive
         ...   
727    positive
728    positive
729    positive
730    positive
731    positive
Name: Sentiment, Length: 732, dtype: object


<ipython-input-39-31d81a2c2814>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Sentiment'] = dataset['Sentiment'].replace(positive_words, 'positive', regex=True, )
<ipython-input-39-31d81a2c2814>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Sentiment'] = dataset['Sentiment'].replace(negative_words, 'negative', regex=True, )
<ipython-input-39-31d81a2c2814>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_inde

In [ ]:
print(dataset['Sentiment'].unique())


['positive' 'negative' 'neutral']


In [ ]:
dataset

Text Sentiment
0     Enjoying a beautiful day at the park!        ...  positive
1     Traffic was terrible this morning.           ...  negative
2     Just finished an amazing workout! 💪          ...  positive
3     Excited about the upcoming weekend getaway!  ...  positive
4     Trying out a new recipe for dinner tonight.  ...  positive
..                                                 ...       ...
727  Collaborating on a science project that receiv...  positive
728  Attending a surprise birthday party organized ...  positive
729  Successfully fundraising for a school charity ...  positive
730  Participating in a multicultural festival, cel...  positive
731  Organizing a virtual talent show during challe...  positive

[732 rows x 2 columns]

In [ ]:
y = dataset['Sentiment']

In [ ]:
y.unique()


array(['positive', 'negative', 'neutral'], dtype=object)

In [ ]:
x = dataset['Text']

In [ ]:
x

0       Enjoying a beautiful day at the park!        ...
1       Traffic was terrible this morning.           ...
2       Just finished an amazing workout! 💪          ...
3       Excited about the upcoming weekend getaway!  ...
4       Trying out a new recipe for dinner tonight.  ...
                             ...                        
727    Collaborating on a science project that receiv...
728    Attending a surprise birthday party organized ...
729    Successfully fundraising for a school charity ...
730    Participating in a multicultural festival, cel...
731    Organizing a virtual talent show during challe...
Name: Text, Length: 732, dtype: object

In [ ]:
columns_to_keep = ['Text' , 'Sentiment']
dataset = dataset[columns_to_keep]

dataset

Text Sentiment
0     Enjoying a beautiful day at the park!        ...  positive
1     Traffic was terrible this morning.           ...  negative
2     Just finished an amazing workout! 💪          ...  positive
3     Excited about the upcoming weekend getaway!  ...  positive
4     Trying out a new recipe for dinner tonight.  ...  positive
..                                                 ...       ...
727  Collaborating on a science project that receiv...  positive
728  Attending a surprise birthday party organized ...  positive
729  Successfully fundraising for a school charity ...  positive
730  Participating in a multicultural festival, cel...  positive
731  Organizing a virtual talent show during challe...  positive

[732 rows x 2 columns]

In [ ]:

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus = []
for i in range(0, 732):
  message = re.sub('[^a-zA-Z]', ' ', dataset['Text'][i])
  message = message.lower()
  message = message.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  message = [ps.stem(word) for word in message if not word in set(all_stopwords)]
  message = ' '.join(message)
  corpus.append(message)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
corpus


['enjoy beauti day park',
 'traffic terribl morn',
 'finish amaz workout',
 'excit upcom weekend getaway',
 'tri new recip dinner tonight',
 'feel grate littl thing life',
 'raini day call cozi blanket hot cocoa',
 'new movi releas must watch',
 'polit discuss heat timelin',
 'miss summer vibe beach day',
 'publish new blog post check',
 'feel bit weather today',
 'explor citi hidden gem',
 'new year new fit goal',
 'technolog chang way live',
 'reflect past look ahead',
 'adopt cute furri friend',
 'late night game session friend',
 'attend virtual confer ai',
 'winter blue got feel low',
 'sip coffe enjoy good book',
 'explor world virtual realiti',
 'product day tick list',
 'finish challeng workout routin',
 'celebr mileston work',
 'sunday brunch friend',
 'learn new languag person growth',
 'quiet even good book',
 'reflect import mental health',
 'new paint progress',
 'weekend road trip explor scenic view',
 'enjoy cup tea watch sunset',
 'code new project enthusiasm',
 'feel i

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

x = cv.fit_transform(corpus).toarray()

y = dataset.iloc[:,0].values
print(x)
print(y)

y = dataset['Sentiment'].map({'positive': 1, 'negative': 2 , 'neutral':3})

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[' Enjoying a beautiful day at the park!              '
 ' Traffic was terrible this morning.                 '
 ' Just finished an amazing workout! 💪               '
 ' Excited about the upcoming weekend getaway!        '
 ' Trying out a new recipe for dinner tonight.        '
 ' Feeling grateful for the little things in life.    '
 ' Rainy days call for cozy blankets and hot cocoa.   '
 ' The new movie release is a must-watch!             '
 ' Political discussions heating up on the timeline.  '
 ' Missing summer vibes and beach days.               '
 ' Just published a new blog post. Check it out!      '
 ' Feeling a bit under the weather today.             '
 " Exploring the city's hidden gems.                  "
 ' New year, new fitness goals! 💪                    '
 ' Technology is changing the way we live.            '
 ' Reflecting on the past and looking ahea

In [ ]:
y


0      1
1      2
2      1
3      1
4      1
      ..
727    1
728    1
729    1
730    1
731    1
Name: Sentiment, Length: 732, dtype: int64

In [ ]:
x


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
len(x[0])

1939

In [ ]:
cv = CountVectorizer(max_features = 1900)

x = cv.fit_transform(corpus).toarray()
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[113   5   0]
 [ 11  11   0]
 [  6   0   1]]


0.8503401360544217

In [ ]:
y_pred

array([1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
while(1):
  new_message = str(input("enter the message: "))
  if(new_message == 'exit'):
    break
  new_message = re.sub('[^a-zA-Z]', ' ', new_message)
  new_message = new_message.lower()
  new_message = new_message.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  new_message = [ps.stem(word) for word in new_message if not word in set(all_stopwords)]
  new_message = ' '.join(new_message)
  new_corpus = [new_message]
  new_X_test = cv.transform(new_corpus).toarray()
  new_y_pred = classifier.predict(new_X_test)


  if(new_y_pred[0] == 1):
    print("the message has positive sentiment ")
  elif(new_y_pred[0] == 2):
    print("the message has negative sentiment ")
  elif(new_y_pred[0] == 3):
    print("the message has a neutral sentiment")


