In [ ]:


from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv('/content/drive/MyDrive/modeol selection/Machine Learning A-Z (Model Selection)/Regression/Data.csv')

In [ ]:
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

we need to determine 'Pe' using the other 4 as features


in future have the last columna as the dependent variable and the oother as the features

Linear Regression:

Characteristics: Linear relationship between dependent and independent variables.
Variables: One dependent variable, one or more independent variables.
Real-Life Applications: Predicting house prices based on square footage, forecasting sales based on advertising spending.

Multiple Regression:

Characteristics: Extension of linear regression for multiple independent variables.
Variables: One dependent variable, two or more independent variables.
Real-Life Applications: Predicting a student's GPA based on study hours, class attendance, and previous grades.

Polynomial Regression:

Characteristics: Fits a polynomial equation to the data.
Variables: One dependent variable, one independent variable (or more with higher degrees).
Real-Life Applications: Modeling the relationship between temperature and gas consumption.

Support Vector Machine (SVM) Regression:

Characteristics: Finds a hyperplane that best represents the data.
Variables: One dependent variable, one or more independent variables.
Real-Life Applications: Stock price prediction, predicting patient outcomes in healthcare.

Decision Tree Regression:

Characteristics: Uses a tree-like model to make decisions.
Variables: One dependent variable, one or more independent variables.
Real-Life Applications: Predicting customer churn, determining salary based on education and experience.

Random Forest Regression:

Characteristics: Ensemble of decision trees for improved accuracy.
Variables: One dependent variable, one or more independent variables.
Real-Life Applications: Predicting customer preferences in marketing, estimating crop yields in agriculture.

**evaluating regression model**

Evaluation metrics;

* Mean/Median of prediction
* Standard Deviation of prediction
* Range of prediction
* Coefficient of Determination (R2)
* Relative Standard Deviation/Coefficient of Variation (RSD)
* Relative Squared Error (RSE)
* Mean Absolute Error (MAE)
* Relative Absolute Error (RAE)
* Mean Squared Error (MSE)
* Root Mean Squared Error on Prediction (RMSE/RMSEP)
* Normalized Root Mean Squared Error (Norm RMSEP)
* Relative Root Mean Squared Error (RRMSEP)


**multiple linear regression**

In [ ]:
dataset1 = pd.read_csv('/content/drive/MyDrive/modeol selection/Machine Learning A-Z (Model Selection)/Regression/Data.csv')
X1 = dataset1.iloc[:, :-1].values
y1 = dataset1.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = 0.2, random_state = 0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X1_train, y1_train)

y1_pred = regressor.predict(X1_test)
np.set_printoptions(precision=2)
print(np.concatenate((y1_pred.reshape(len(y1_pred),1), y1_test.reshape(len(y1_test),1)),1))

from sklearn.metrics import r2_score
mlr=r2_score(y1_test, y1_pred)
mlr

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


0.9325315554761303

**polynomial regression**

In [ ]:
dataset2 = pd.read_csv('/content/drive/MyDrive/modeol selection/Machine Learning A-Z (Model Selection)/Regression/Data.csv')
X2 = dataset2.iloc[:, :-1].values
y2 = dataset2.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X2_poly = poly_reg.fit_transform(X2_train)
regressor = LinearRegression()
regressor.fit(X2_poly, y2_train)

y2_pred = regressor.predict(poly_reg.transform(X2_test))
np.set_printoptions(precision=2)
print(np.concatenate((y2_pred.reshape(len(y2_pred),1), y2_test.reshape(len(y2_test),1)),1))

from sklearn.metrics import r2_score
plr=r2_score(y2_test, y2_pred)
plr

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


0.9458192809530098

**svm regression**

In [ ]:
dataset3 = pd.read_csv('/content/drive/MyDrive/modeol selection/Machine Learning A-Z (Model Selection)/Regression/Data.csv')
X3 = dataset3.iloc[:, :-1].values
y3 = dataset3.iloc[:, -1].values

y3 = y3.reshape(len(y3),1)

from sklearn.model_selection import train_test_split
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc_X3 = StandardScaler()
sc_y3 = StandardScaler()
X3_train = sc_X3.fit_transform(X3_train)
y3_train = sc_y3.fit_transform(y3_train)

from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X3_train, y3_train)

y3_pred = sc_y3.inverse_transform(regressor.predict(sc_X3.transform(X3_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y3_pred.reshape(len(y3_pred),1), y3_test.reshape(len(y3_test),1)),1))

from sklearn.metrics import r2_score
svmr=r2_score(y3_test, y3_pred)
svmr

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


0.9480784049986258

**decision tree regression**

In [ ]:
dataset4 = pd.read_csv('/content/drive/MyDrive/modeol selection/Machine Learning A-Z (Model Selection)/Regression/Data.csv')
X4 = dataset4.iloc[:, :-1].values
y4 = dataset4.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size = 0.2, random_state = 0)

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X4_train, y4_train)

y4_pred = regressor.predict(X4_test)
np.set_printoptions(precision=2)
print(np.concatenate((y4_pred.reshape(len(y4_pred),1), y4_test.reshape(len(y4_test),1)),1))

from sklearn.metrics import r2_score
dtr=r2_score(y4_test, y4_pred)
dtr

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


0.922905874177941

**random forest regression**

In [ ]:
dataset5 = pd.read_csv('/content/drive/MyDrive/modeol selection/Machine Learning A-Z (Model Selection)/Regression/Data.csv')
X5 = dataset5.iloc[:, :-1].values
y5 = dataset5.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X5_train, X5_test, y5_train, y5_test = train_test_split(X5, y5, test_size = 0.2, random_state = 0)

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X5_train, y5_train)

y5_pred = regressor.predict(X5_test)
np.set_printoptions(precision=2)
print(np.concatenate((y5_pred.reshape(len(y5_pred),1), y5_test.reshape(len(y5_test),1)),1))

from sklearn.metrics import r2_score
rfr=r2_score(y5_test, y5_pred)
rfr

[[434.05 431.23]
 [458.79 460.01]
 [463.02 461.14]
 ...
 [469.48 473.26]
 [439.57 438.  ]
 [460.38 463.28]]


0.9615908334363876

In [ ]:
print("r2 score of the following:")
print("multiple linear regression",mlr)
print("polynomial linear regression",plr)
print("svm regression",svmr)
print("decision tree regression",dtr)
print("random forest regression",rfr)


r2 score of the following:
multiple linear regression 0.9325315554761303
polynomial linear regression 0.9458192809530098
svm regression 0.9480784049986258
decision tree regression 0.922905874177941
random forest regression 0.9615908334363876
